---
  - become: true
    gather_facts: true
    hosts: all
    name: Converge
    pre_tasks:
      - ansible.builtin.apt: update_cache=true cache_valid_time=600
        changed_when: false
        name: Update apt cache.
        when: ansible_os_family == 'Debian'
    roles:
      - role: buluma.go
    tasks:
      - ansible.builtin.command: go version
        changed_when: false
        environment:
          PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        name: Verify that Go is installed and available in the $PATH.
