---
- name: Converge
  become: true
  gather_facts: true
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: "true"
        cache_valid_time: "600"
      changed_when: false
      when: ansible_os_family == 'Debian'
  roles:
    - role: buluma.go
  tasks:
    - name: Verify that Go is installed and available in the $PATH.
      ansible.builtin.command: go version
      changed_when: false
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
