---
- name: Prepare
  become: true
  gather_facts: false
  hosts: all
  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.buildtools
    - role: buluma.ca_certificates
